name: Build and deploy Node.js app to Azure Web App - wis

on:
  push:
    branches:
      - implementation
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies and test
        working-directory: implementation/backend
        run: |
          npm ci
          npm test --if-present

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AB804782AC684DEF9986939D821062DF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_09FEE545668041D49D0FBA040526DF2D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A328ED4147F34EC8A7AD48C01241BECE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: wis
          slot-name: Production
          package: ./implementation/backend
